kind: pipeline
name: default

steps:
- name: frontend
  image: node:8
  commands:
  - cd public && npm install
  - npm run build

- name: deploy
  image: appleboy/drone-ssh
  pull: true
  settings:
    host:
      from_secret: host
    user:
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    port: 22
    command_timeout: 180
    script:
      - cd /deploy/spendee  # or whereever you put your `deploy.sh`
      - sh deploy.sh
  when:
    branch:
      - master
    event: [push, tag, deployment, pull_request]
