version: "3"
services:
  web:
    image: hub.tich.us/tawazz/spendee:latest
    volumes:
      - .:/app
    ports:
      - "8001:80"
    networks:
      - webnet
    restart: always
networks:
  webnet:
